name: Release to Production

on:
  push:
    branches: [main, heroku-test-branch]

env:
  DOCKER_REGISTRY: registry.heroku.com
  HEROKU_PROCESS_TYPE: web
  APP_NAME: tamu-capstone-2021

jobs:
  release:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Restore Docker cache
        uses: actions/cache@v2
        env:
          cache-base: v1-${{ runner.os }}-cache-docker
        with:
          path: /tmp/.buildx-cache
          key: ${{ env.cache-base }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-base }}-

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}/${{ env.HEROKU_PROCESS_TYPE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Heroku Set Config and release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          APP_URL=`heroku apps:info ${{ env.APP_NAME }} -s | grep web_url | cut -d= -f2`
          APP_URL=${APP_URL%/}

          heroku config:set --app ${{ env.APP_NAME }} \
            NODE_ENV=production

          heroku container:release ${{ env.HEROKU_PROCESS_TYPE }} --app ${{ env.APP_NAME }}
